### ISSUE TITLE
Upgrade React Router

### ISSUE THREAD

**Issue by FranckCo** [FranckCo/Operation-Explorer#3]
React Router was downgraded to an older version due to problems in route definitions

**Comment by ghost** [comment]
Fixed with e5e7e888355787beba36829584afaa9ef215ea5a. Upgrading react-router required to refactor all the route definition mechanism (including the way we shorten URI to embed them in routes). It also had some consequences on the authentication process.

**Comment by FranckCo** [comment]
Fix validated
