### ISSUE TITLE
Non existing URLs should return 404

### ISSUE THREAD

**Issue by FranckCo** [FranckCo/Operation-Explorer#9]
Currently, there is an error message coming from SPARQL Connect (Error: One result was expected but no result was found), see for example /operations/operation/blah.
Also, non-existing routes result in a blank page with just the menu (try /cheese). They should also return 404.

**Comment by ghost** [comment]
I assume you mean client side 404 like pages (not real 404 responses which require server configuration, to catch non existing routes, and logic, to catch valid routes referring to a non existing entity). Don't you ?
